case class A0(i: Int, s: String) derives Print
case class A1(i: Int, s: String) derives Print
case class A2(i: Int, s: String) derives Print
case class A3(i: Int, s: String) derives Print
case class A4(i: Int, s: String) derives Print
case class A5(i: Int, s: String) derives Print
case class A6(i: Int, s: String) derives Print
case class A7(i: Int, s: String) derives Print
case class A8(i: Int, s: String) derives Print
case class A9(i: Int, s: String) derives Print
case class A10(i: Int, s: String) derives Print
case class A11(i: Int, s: String) derives Print
case class A12(i: Int, s: String) derives Print
case class A13(i: Int, s: String) derives Print
case class A14(i: Int, s: String) derives Print
case class A15(i: Int, s: String) derives Print
case class A16(i: Int, s: String) derives Print
case class A17(i: Int, s: String) derives Print
case class A18(i: Int, s: String) derives Print
case class A19(i: Int, s: String) derives Print
case class A20(i: Int, s: String) derives Print
case class A21(i: Int, s: String) derives Print
case class A22(i: Int, s: String) derives Print
case class A23(i: Int, s: String) derives Print
case class A24(i: Int, s: String) derives Print
case class A25(i: Int, s: String) derives Print
case class A26(i: Int, s: String) derives Print
case class A27(i: Int, s: String) derives Print
case class A28(i: Int, s: String) derives Print
case class A29(i: Int, s: String) derives Print
case class A30(i: Int, s: String) derives Print
case class A31(i: Int, s: String) derives Print
case class A32(i: Int, s: String) derives Print
case class A33(i: Int, s: String) derives Print
case class A34(i: Int, s: String) derives Print
case class A35(i: Int, s: String) derives Print
case class A36(i: Int, s: String) derives Print
case class A37(i: Int, s: String) derives Print
case class A38(i: Int, s: String) derives Print
case class A39(i: Int, s: String) derives Print
case class A40(i: Int, s: String) derives Print
case class A41(i: Int, s: String) derives Print
case class A42(i: Int, s: String) derives Print
case class A43(i: Int, s: String) derives Print
case class A44(i: Int, s: String) derives Print
case class A45(i: Int, s: String) derives Print
case class A46(i: Int, s: String) derives Print
case class A47(i: Int, s: String) derives Print
case class A48(i: Int, s: String) derives Print
case class A49(i: Int, s: String) derives Print
case class A50(i: Int, s: String) derives Print
case class A51(i: Int, s: String) derives Print
case class A52(i: Int, s: String) derives Print
case class A53(i: Int, s: String) derives Print
case class A54(i: Int, s: String) derives Print
case class A55(i: Int, s: String) derives Print
case class A56(i: Int, s: String) derives Print
case class A57(i: Int, s: String) derives Print
case class A58(i: Int, s: String) derives Print
case class A59(i: Int, s: String) derives Print
case class A60(i: Int, s: String) derives Print
case class A61(i: Int, s: String) derives Print
case class A62(i: Int, s: String) derives Print
case class A63(i: Int, s: String) derives Print
case class A64(i: Int, s: String) derives Print
case class A65(i: Int, s: String) derives Print
case class A66(i: Int, s: String) derives Print
case class A67(i: Int, s: String) derives Print
case class A68(i: Int, s: String) derives Print
case class A69(i: Int, s: String) derives Print
case class A70(i: Int, s: String) derives Print
case class A71(i: Int, s: String) derives Print
case class A72(i: Int, s: String) derives Print
case class A73(i: Int, s: String) derives Print
case class A74(i: Int, s: String) derives Print
case class A75(i: Int, s: String) derives Print
case class A76(i: Int, s: String) derives Print
case class A77(i: Int, s: String) derives Print
case class A78(i: Int, s: String) derives Print
case class A79(i: Int, s: String) derives Print
case class A80(i: Int, s: String) derives Print
case class A81(i: Int, s: String) derives Print
case class A82(i: Int, s: String) derives Print
case class A83(i: Int, s: String) derives Print
case class A84(i: Int, s: String) derives Print
case class A85(i: Int, s: String) derives Print
case class A86(i: Int, s: String) derives Print
case class A87(i: Int, s: String) derives Print
case class A88(i: Int, s: String) derives Print
case class A89(i: Int, s: String) derives Print
case class A90(i: Int, s: String) derives Print
case class A91(i: Int, s: String) derives Print
case class A92(i: Int, s: String) derives Print
case class A93(i: Int, s: String) derives Print
case class A94(i: Int, s: String) derives Print
case class A95(i: Int, s: String) derives Print
case class A96(i: Int, s: String) derives Print
case class A97(i: Int, s: String) derives Print
case class A98(i: Int, s: String) derives Print
case class A99(i: Int, s: String) derives Print
case class A100(i: Int, s: String) derives Print
case class A101(i: Int, s: String) derives Print
case class A102(i: Int, s: String) derives Print
case class A103(i: Int, s: String) derives Print
case class A104(i: Int, s: String) derives Print
case class A105(i: Int, s: String) derives Print
case class A106(i: Int, s: String) derives Print
case class A107(i: Int, s: String) derives Print
case class A108(i: Int, s: String) derives Print
case class A109(i: Int, s: String) derives Print
case class A110(i: Int, s: String) derives Print
case class A111(i: Int, s: String) derives Print
case class A112(i: Int, s: String) derives Print
case class A113(i: Int, s: String) derives Print
case class A114(i: Int, s: String) derives Print
case class A115(i: Int, s: String) derives Print
case class A116(i: Int, s: String) derives Print
case class A117(i: Int, s: String) derives Print
case class A118(i: Int, s: String) derives Print
case class A119(i: Int, s: String) derives Print
case class A120(i: Int, s: String) derives Print
case class A121(i: Int, s: String) derives Print
case class A122(i: Int, s: String) derives Print
case class A123(i: Int, s: String) derives Print
case class A124(i: Int, s: String) derives Print
case class A125(i: Int, s: String) derives Print
case class A126(i: Int, s: String) derives Print
case class A127(i: Int, s: String) derives Print
case class A128(i: Int, s: String) derives Print
case class A129(i: Int, s: String) derives Print
case class A130(i: Int, s: String) derives Print
case class A131(i: Int, s: String) derives Print
case class A132(i: Int, s: String) derives Print
case class A133(i: Int, s: String) derives Print
case class A134(i: Int, s: String) derives Print
case class A135(i: Int, s: String) derives Print
case class A136(i: Int, s: String) derives Print
case class A137(i: Int, s: String) derives Print
case class A138(i: Int, s: String) derives Print
case class A139(i: Int, s: String) derives Print
case class A140(i: Int, s: String) derives Print
case class A141(i: Int, s: String) derives Print
case class A142(i: Int, s: String) derives Print
case class A143(i: Int, s: String) derives Print
case class A144(i: Int, s: String) derives Print
case class A145(i: Int, s: String) derives Print
case class A146(i: Int, s: String) derives Print
case class A147(i: Int, s: String) derives Print
case class A148(i: Int, s: String) derives Print
case class A149(i: Int, s: String) derives Print
case class A150(i: Int, s: String) derives Print
case class A151(i: Int, s: String) derives Print
case class A152(i: Int, s: String) derives Print
case class A153(i: Int, s: String) derives Print
case class A154(i: Int, s: String) derives Print
case class A155(i: Int, s: String) derives Print
case class A156(i: Int, s: String) derives Print
case class A157(i: Int, s: String) derives Print
case class A158(i: Int, s: String) derives Print
case class A159(i: Int, s: String) derives Print
case class A160(i: Int, s: String) derives Print
case class A161(i: Int, s: String) derives Print
case class A162(i: Int, s: String) derives Print
case class A163(i: Int, s: String) derives Print
case class A164(i: Int, s: String) derives Print
case class A165(i: Int, s: String) derives Print
case class A166(i: Int, s: String) derives Print
case class A167(i: Int, s: String) derives Print
case class A168(i: Int, s: String) derives Print
case class A169(i: Int, s: String) derives Print
case class A170(i: Int, s: String) derives Print
case class A171(i: Int, s: String) derives Print
case class A172(i: Int, s: String) derives Print
case class A173(i: Int, s: String) derives Print
case class A174(i: Int, s: String) derives Print
case class A175(i: Int, s: String) derives Print
case class A176(i: Int, s: String) derives Print
case class A177(i: Int, s: String) derives Print
case class A178(i: Int, s: String) derives Print
case class A179(i: Int, s: String) derives Print
case class A180(i: Int, s: String) derives Print
case class A181(i: Int, s: String) derives Print
case class A182(i: Int, s: String) derives Print
case class A183(i: Int, s: String) derives Print
case class A184(i: Int, s: String) derives Print
case class A185(i: Int, s: String) derives Print
case class A186(i: Int, s: String) derives Print
case class A187(i: Int, s: String) derives Print
case class A188(i: Int, s: String) derives Print
case class A189(i: Int, s: String) derives Print
case class A190(i: Int, s: String) derives Print
case class A191(i: Int, s: String) derives Print
case class A192(i: Int, s: String) derives Print
case class A193(i: Int, s: String) derives Print
case class A194(i: Int, s: String) derives Print
case class A195(i: Int, s: String) derives Print
case class A196(i: Int, s: String) derives Print
case class A197(i: Int, s: String) derives Print
case class A198(i: Int, s: String) derives Print
case class A199(i: Int, s: String) derives Print
case class A200(i: Int, s: String) derives Print

